name: VotingLevels
version: '${project.version}'
main: lv.cliquant.votinglevels.VotingLevels
api-version: '1.21.4'
authors:
  - "Cliquant"
load: STARTUP
dependencies:
  server:
    VotingPlugin:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true