#########################
#                       #
#     VOTING LEVELS     #
#                       #
#########################

# PlaceholdersAPI:%votinglevels_PLAYER_level%, %votinglevels_PLAYER_votes%, %votinglevels_PLAYER_needvotes%, %votinglevels_PLAYER_rewardstext%, %votinglevels_PLAYER_itemtitle%, %votinglevels_PLAYER_itemlore%

# {player_name}, {player_name}, {current_level} = local placeholders

messages:
  player-notfound: "<red>Player not found or has never played on this server."
  no-access: "<red>You have no access for this command."
  finished-levels: "<white>There's no voting level anymore, you <color:#cfcfcf>finished<white> all of them."
  achieved-level: "<white>You achieved voting level <color:#cfcfcf>{level}<white>. Use <color:#cfcfcf>/votinglevels<white> to redeem it!"
  redeemed-level: "<white>You redeemed voting level <color:#cfcfcf>{level}<white>"

gui:
  cant:
    title: "<color:#005400>VOTING LEVEL <color:#cfcfcf>%votinglevels_{player_name}_level%"
    lore:
      - "<white>LEVEL</white> <color:#cfcfcf>%votinglevels_{player_name}_level%"
      - "<white>Requirement</white> <color:#cfcfcf>%votinglevels_{player_name}_votes%/%votinglevels_{player_name}_needvotes% <white>votes"
      - "<white>You have</white> <color:#cfcfcf>%votinglevels_{player_name}_votes%<white> votes"
      - ""
      - "<color:#cfcfcf>REWARDS"
      - "{rewards_text}"
  can:
    title: "<color:#005400>VOTING LEVEL <color:#cfcfcf>%votinglevels_{player_name}_level%"
    lore:
      - "<white>LEVEL</white> <color:#cfcfcf>%votinglevels_{player_name}_level%"
      - "<white>Requirement</white> <color:#cfcfcf>%votinglevels_{player_name}_votes%/%votinglevels_{player_name}_needvotes% <white>votes"
      - "<white>You have</white> <color:#cfcfcf>%votinglevels_{player_name}_votes% votes"
      - ""
      - "<color:#cfcfcf>REWARDS"
      - "{rewards_text}"
      - ""
      - "<white>CLICK TO REDEEM REWARD</white>"

levels: # placeholders for reward commands: {level}, {needvotes}
  1:
    req: 5
    reward-text:
      - "<white>BALANCE <green>+$15000</green><white> | (level * 15000)"
    commands:
      - "broadcast {player_name} broadcast from votinglevels!"
      - "eco give {player_name} %Math_{level}*15000%"